name: PR Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

  build:
    name: Build
    needs: validate-wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 17

      - name: Set up Gradle wrapper cache
        id: wrapper-cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Set up Gradle dependency cache
        id: dependency-cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Run tests
        run: ./gradlew check

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports

      - name: Run analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube

      - name: Assemble
        run: ./gradlew assemble
        if: github.ref == 'refs/heads/master'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: jar
          path: build/libs/*.jar
